In [1]:
import numpy as np

c:\users\personal\appdata\local\programs\python\python38\lib\site-packages\numpy\_distributor_init.py:30: UserWarning: loaded more than 1 DLL from .libs:
c:\users\personal\appdata\local\programs\python\python38\lib\site-packages\numpy\.libs\libopenblas.NOIJJG62EMASZI6NYURL6JBKM4EVBGM7.gfortran-win_amd64.dll
c:\users\personal\appdata\local\programs\python\python38\lib\site-packages\numpy\.libs\libopenblas.WCDJNK7YVMPZQ2ME2ZZHJJRJ3JIKNDB7.gfortran-win_amd64.dll
  warnings.warn("loaded more than 1 DLL from .libs:"


In [4]:
a = np.array([[1,2,3,4,5],[6,7,8,9,10]])

In [5]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [8]:
b = np.array([[[1,2,3,4,5],[5,6,7,8,9]],[[8,9,7,5,6],[9,8,7,4,5]]])

In [9]:
b

array([[[1, 2, 3, 4, 5],
        [5, 6, 7, 8, 9]],

       [[8, 9, 7, 5, 6],
        [9, 8, 7, 4, 5]]])

In [11]:
b.ndim

3

# Indexing

In [15]:
a[0] , a[1]

(array([1, 2, 3, 4, 5]), array([ 6,  7,  8,  9, 10]))

In [20]:
a[0,2]

3

In [21]:
a[1,4]

10

In [19]:
b[0],b[1],

(array([[1, 2, 3, 4, 5],
        [5, 6, 7, 8, 9]]),
 array([[8, 9, 7, 5, 6],
        [9, 8, 7, 4, 5]]))

In [22]:
b[0,1]

array([5, 6, 7, 8, 9])

In [23]:
b[0,1,2]

7

# Slicing

In [24]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [26]:
a[0,0:2]

array([1, 2])

In [33]:
a[0:2,0:3]

array([[1, 2, 3],
       [6, 7, 8]])

In [37]:
a[0,0] = 1

In [38]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [41]:
a.shape   #contaims 2dimension and each has 5 elements

(2, 5)

In [42]:
a.reshape(5,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

# Iterating

In [46]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [44]:
for x in a:
    print(x)

[1 2 3 4 5]
[ 6  7  8  9 10]


In [45]:
for x in a:
    for y in x:
        print(y)

1
2
3
4
5
6
7
8
9
10


In [48]:
for x in np.nditer(a):
    print (x)                                # using nditer function

1
2
3
4
5
6
7
8
9
10


In [49]:
for idx, x in np.ndenumerate(a):
    print(idx,x)

(0, 0) 1
(0, 1) 2
(0, 2) 3
(0, 3) 4
(0, 4) 5
(1, 0) 6
(1, 1) 7
(1, 2) 8
(1, 3) 9
(1, 4) 10


In [50]:
c = np.array([[6,5,4,7,8],[3,2,1,4,5]])

In [51]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

# Joins

In [64]:
arr =np.concatenate((a,c),axis=0)

In [65]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [ 6,  5,  4,  7,  8],
       [ 3,  2,  1,  4,  5]])

In [66]:
arr =np.concatenate((a,c),axis=1)

In [67]:
arr

array([[ 1,  2,  3,  4,  5,  6,  5,  4,  7,  8],
       [ 6,  7,  8,  9, 10,  3,  2,  1,  4,  5]])

# Split

In [80]:
arr = np.array_split(a,4)

In [81]:
arr

[array([[1, 2, 3, 4, 5]]),
 array([[ 6,  7,  8,  9, 10]]),
 array([], shape=(0, 5), dtype=int32),
 array([], shape=(0, 5), dtype=int32)]

# Where

In [127]:
x= np.array([5,6,8,9])

In [128]:
x =np.where(x>6)

In [129]:
x

(array([2, 3], dtype=int64),)

In [92]:
b

array([[[1, 2, 3, 4, 5],
        [5, 6, 7, 8, 9]],

       [[8, 9, 7, 5, 6],
        [9, 8, 7, 4, 5]]])

# Sorting

In [93]:
print(np.sort(b))

[[[1 2 3 4 5]
  [5 6 7 8 9]]

 [[5 6 7 8 9]
  [4 5 7 8 9]]]


# Filter

In [111]:
g = np.array([8,9,7,5,6,4])
filter =[]

In [103]:
for x in g :
    if x>5:
     filter.append(True)
    else:
     filter.append(False)

In [105]:
new = g[filter]

In [106]:
new

array([8, 9, 7, 6])

# Rounding

In [114]:
gg = np.fix([-254.23,356.58])

In [115]:
gg

array([-254.,  356.])

In [116]:
floor = np.floor([-56.32,89.32])

In [117]:
floor

array([-57.,  89.])

In [118]:
ceil = np.ceil([-96.24,89.3])

In [119]:
ceil

array([-96.,  90.])